apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: node-service
  template:
    metadata:
      labels:
        app: node-service
    spec:
      containers:
        - name: node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
