apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: { { .Values.service.type } }
  selector:
    app: node-service
  ports:
    - port: { { .Values.service.port } }
      targetPort: 3000
